# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               iloveulhj's Blog
tagline:             iloveulhj@gmail.com
description:         This blog used <br> <a href="https://github.com">Github</a>, <a href="http://jekyllrb.com">Jekyll</a>, <a href="https://github.com/poole/poole">Poole</a>(Jekyll theme)
url:                 https://iloveulhj.github.com
baseurl:             /
paginate:            1

# About/contact
author:
  name:              hojungLee
  url:
  email:             iloveulhj@gmail.com

# Custom vars
version:             1.0.0-SNAPSHOT
